# Generated by Django 4.2.1 on 2023-06-03 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "duration_min",
                    models.IntegerField(
                        help_text="Desired number of minutes at a time.",
                        verbose_name="Desired Duration (minutes)",
                    ),
                ),
                (
                    "unit_time",
                    models.CharField(
                        choices=[("D", "Day"), ("W", "Week"), ("M", "Month")],
                        default="W",
                        help_text="The time interval to measure your goal against.",
                        max_length=1,
                        verbose_name="Unit of Time",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                (
                    "duration_mins",
                    models.IntegerField(
                        help_text="The time spent in minutes",
                        verbose_name="Duration (mins)",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracking.goal"
                    ),
                ),
            ],
        ),
    ]
