# Generated by Django 4.2.1 on 2023-06-03 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="goal",
            name="start_date",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="duration_mins",
            field=models.IntegerField(
                help_text="The time spent in minutes",
                null=True,
                verbose_name="Duration (mins)",
            ),
        ),
    ]
