# Generated by Django 4.2.1 on 2023-06-03 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0003_alter_goal_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="tracking.goal",
            ),
        ),
    ]
